name: Node.js Package

on:
  push:
    tags:
    - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install --only=dev
      - run: npm run build
      - run: make build-with-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
